<#
.SYNOPSIS
Publishes the generated obs-auto-framing release zip and checksum as GitHub Release assets.

.DESCRIPTION
By default this script performs a safe dry run and prints the GitHub CLI command it would run.
Pass -Publish to actually create the release. Release artifacts are generated by
scripts/package_release.ps1 and remain ignored by git.
#>
param(
    [string]$Tag,

    [string]$Title,

    [string]$OutputDir = "out/release",

    [string]$NotesPath,

    [switch]$NoAuthCheck,

    [switch]$Publish
)

$ErrorActionPreference = "Stop"

function ConvertTo-ProjectPath {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Path
    )

    if ([System.IO.Path]::IsPathRooted($Path)) {
        return [System.IO.Path]::GetFullPath($Path)
    }

    return [System.IO.Path]::GetFullPath((Join-Path $script:ProjectRoot $Path))
}

function Resolve-RequiredFile {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Path,

        [Parameter(Mandatory = $true)]
        [string]$Description
    )

    if (-not (Test-Path -LiteralPath $Path -PathType Leaf)) {
        throw "$Description not found: $Path"
    }

    return (Resolve-Path -LiteralPath $Path).Path
}

function Quote-Argument {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Argument
    )

    if ($Argument -match '^[A-Za-z0-9_./:=+-]+$') {
        return $Argument
    }

    return '"' + ($Argument -replace '"', '\"') + '"'
}

function Format-CommandLine {
    param(
        [Parameter(Mandatory = $true)]
        [string[]]$Arguments
    )

    return ($Arguments | ForEach-Object { Quote-Argument -Argument $_ }) -join " "
}

$script:ProjectRoot = (Resolve-Path -LiteralPath (Join-Path $PSScriptRoot "..")).Path
$buildspecPath = Resolve-RequiredFile -Path (Join-Path $ProjectRoot "buildspec.json") -Description "Build metadata"
$buildspec = Get-Content -Raw -LiteralPath $buildspecPath | ConvertFrom-Json

$pluginName = [string]$buildspec.name
$version = [string]$buildspec.version
$displayName = [string]$buildspec.displayName
$releaseChannel = [string]$buildspec.releaseChannel

if ([string]::IsNullOrWhiteSpace($pluginName)) {
    throw "Build metadata is missing name."
}
if ([string]::IsNullOrWhiteSpace($version)) {
    throw "Build metadata is missing version."
}
if ([string]::IsNullOrWhiteSpace($displayName)) {
    $displayName = $pluginName
}
if ([string]::IsNullOrWhiteSpace($releaseChannel)) {
    $releaseChannel = "Preview"
}

if ([string]::IsNullOrWhiteSpace($Tag)) {
    $Tag = "v$version"
}
if ([string]::IsNullOrWhiteSpace($Title)) {
    $Title = "$displayName v$version $releaseChannel"
}
if ([string]::IsNullOrWhiteSpace($NotesPath)) {
    $NotesPath = "docs/release_notes/$Tag.md"
}

$outputDirPath = ConvertTo-ProjectPath -Path $OutputDir
$zipPath = Resolve-RequiredFile -Path (Join-Path $outputDirPath "$pluginName-$Tag-windows-x64.zip") -Description "Release zip"
$checksumPath = Resolve-RequiredFile -Path "$zipPath.sha256" -Description "Release checksum"
$notesPathResolved = Resolve-RequiredFile -Path (ConvertTo-ProjectPath -Path $NotesPath) -Description "Release notes"

$isPreview = $releaseChannel -ieq "Preview" -or $version -eq "0.1.0"
$releaseArgs = @(
    "release",
    "create",
    $Tag,
    $zipPath,
    $checksumPath,
    "--title",
    $Title,
    "--notes-file",
    $notesPathResolved
)
if ($isPreview) {
    $releaseArgs += "--prerelease"
}

$commandPreview = "gh " + (Format-CommandLine -Arguments $releaseArgs)

if ($Publish -and $NoAuthCheck) {
    throw "-NoAuthCheck can only be used for dry runs."
}

if (-not $NoAuthCheck) {
    $ghCommand = Get-Command gh -ErrorAction SilentlyContinue
    if ($null -eq $ghCommand) {
        throw "GitHub CLI 'gh' was not found on PATH. Install it from https://cli.github.com/ and run 'gh auth login'."
    }

    & gh auth status *> $null
    if ($LASTEXITCODE -ne 0) {
        throw "GitHub CLI authentication failed. Run 'gh auth login' and try again."
    }
}

if (-not $Publish) {
    Write-Host "Dry run only. Pass -Publish to create the GitHub Release."
    if ($NoAuthCheck) {
        Write-Host "GitHub CLI install/auth checks were skipped for this dry run."
    }
    Write-Host ""
    Write-Host "Validated release assets:"
    Write-Host "  $zipPath"
    Write-Host "  $checksumPath"
    Write-Host "Release notes:"
    Write-Host "  $notesPathResolved"
    Write-Host ""
    Write-Host "Command that would be run:"
    Write-Host $commandPreview
    exit 0
}

Write-Host "Creating GitHub Release $Tag..."
Write-Host $commandPreview
& gh @releaseArgs
if ($LASTEXITCODE -ne 0) {
    throw "GitHub Release publishing failed with exit code $LASTEXITCODE."
}

Write-Host "GitHub Release published: $Tag"
